youtube_app/urls.py
from django.urls import path

from youtube_app import views

urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
    path('fetch/', views.insert_url, name='cfetch'),
    path('analysis/', views.sanalysis, name='sanalysis'),
    path('detection/', views.sdetection, name='sdetection'),
    path('about/', views.aboutus, name='aboutus'),
    path('model/', views.models, name='models'),
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    # other URL patterns
    path('fetch-comm/', views.fetch_comments, name='fetch-comm'),
    path('eng-comments/<str:video_id>/', views.fetch_eng_comments, name='fetch-eng'),
    path('emoji-comments/<str:video_id>/', views.fetch_emoji_comments, name='fetch-emoji'),
    path('abc/', views.abc, name='abc'),
    path('avisualize/', views.visualization, name='a-visualize'),
    path('svisualize/', views.spamvisualization, name='s-visualize'),
    path('sentiment-analysis/', views.sentiment_analysis, name='sentiment_analysis'),
    path('spam-detection/', views.spam_detection, name='spam_detection')
]

youtube_sentiment_analysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('youtube_app.urls'))
]

youtube_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import re

class User(AbstractUser):
    email = models.EmailField(max_length=254, unique=True)


class YoutubeVideoId(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    video_url = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.id}'


class Comments(models.Model):
    comment_id = models.CharField(max_length=255)
    video_id = models.ForeignKey(YoutubeVideoId, related_name='comment_video', on_delete=models.CASCADE)
    original_text = models.TextField()
    parent_id = models.CharField(max_length=255, default=None)
    author_name = models.CharField(max_length=255)
    channel_id = models.CharField(max_length=255)
    published_at = models.DateTimeField()
    created_at = models.DateField(default=None)
    update_at = models.DateTimeField()
    label = models.CharField(max_length=255, default=None)
    spamlabel = models.CharField(max_length=255, default=None)

    def __str__(self):
        return f'{self.video_id} - {self.author_name} - {self.channel_id}'


# model for EnglishComments
class EnglishComment(models.Model):
    comment_id = models.CharField(max_length=255)
    video_id = models.ForeignKey(YoutubeVideoId, related_name='encomment_video', on_delete=models.CASCADE)
    original_text = models.TextField()
    parent_id = models.CharField(max_length=255, default=None)
    author_name = models.CharField(max_length=255)
    channel_id = models.CharField(max_length=255)
    published_at = models.DateTimeField()
    created_at = models.DateField(default=None)
    update_at = models.DateTimeField()
    label = models.CharField(max_length=255, default=None)

    def __str__(self):
        return f'{self.video_id} - {self.author_name} - {self.channel_id}'




# model for Emojies
class EmojiesInComments(models.Model):
    comment_id = models.CharField(max_length=255)
    video_id = models.ForeignKey(YoutubeVideoId, related_name='emcomment_video', on_delete=models.CASCADE)
    original_text = models.TextField()
    parent_id = models.CharField(max_length=255, default=None)
    author_name = models.CharField(max_length=255)
    channel_id = models.CharField(max_length=255)
    published_at = models.DateTimeField()
    created_at = models.DateField(default=None)
    update_at = models.DateTimeField()
    label = models.CharField(max_length=255, default=None)

    def __str__(self):
        return f'{self.video_id} - {self.author_name} - {self.channel_id}'


class EmojiesClean(models.Model):
    comment_id = models.CharField(max_length=255)
    video_id = models.ForeignKey(YoutubeVideoId, related_name='eccomment_video', on_delete=models.CASCADE)
    original_text = models.TextField()
    parent_id = models.CharField(max_length=255, default=None)
    author_name = models.CharField(max_length=255)
    channel_id = models.CharField(max_length=255)
    published_at = models.DateTimeField()
    created_at = models.DateField(default=None)
    update_at = models.DateTimeField()
    label = models.CharField(max_length=255, default=None)

    def __str__(self):
        return f'{self.video_id} - {self.author_name} - {self.channel_id}'



class CleanedComment(models.Model):
    comment_id = models.CharField(max_length=255)
    video_id = models.ForeignKey(YoutubeVideoId, related_name='ccomment_video', on_delete=models.CASCADE)
    original_text = models.TextField()
    parent_id = models.CharField(max_length=255, default=None)
    author_name = models.CharField(max_length=255)
    channel_id = models.CharField(max_length=255)
    published_at = models.DateTimeField()
    created_at = models.DateField(default=None)
    update_at = models.DateTimeField()
    cleaned_date = models.DateTimeField(auto_now_add=True)
    label = models.CharField(max_length=255, default=None)
    # Add any other fields you need

    def __str__(self):
        return f'{self.video_id} - {self.author_name} - {self.channel_id}'


class SpamCleanComment(models.Model):
    comment_id = models.CharField(max_length=255)
    video_id = models.ForeignKey(YoutubeVideoId, related_name='scomment_video', on_delete=models.CASCADE)
    original_text = models.TextField()
    parent_id = models.CharField(max_length=255, default=None)
    author_name = models.CharField(max_length=255)
    channel_id = models.CharField(max_length=255)
    published_at = models.DateTimeField()
    created_at = models.DateField(default=None)
    update_at = models.DateTimeField()
    cleaned_date = models.DateTimeField(auto_now_add=True)
    label = models.CharField(max_length=255, default=None)
    spamlabel = models.CharField(max_length=255, default=None)
    # Add any other fields you need

    def __str__(self):
        return f'{self.video_id} - {self.author_name} - {self.channel_id}'

youtube_app/forms.py
import django
from django import forms
from .models import YoutubeVideoId
from .models import User

Customer = 1
CT_Provider = 0
CITY_NAME_CHOICES = (
    (Customer, 'Customer'),
    (CT_Provider, 'CT Provider')
)
class BasicRegForm(django.forms.ModelForm):
    username = django.forms.CharField(
        min_length=4, max_length=15,
        widget=django.forms.TextInput(attrs={'class': 'input', 'placeholder': 'username', 'style': 'color: lightgrey;'})
    )
    email = django.forms.EmailField(
        min_length=6, max_length=40,
        widget=django.forms.TextInput(attrs={'class': 'input', 'placeholder': '@gmail.com', 'style': 'color: lightgrey;'})
    )
    password = django.forms.CharField(
        min_length=6, max_length=20,
        widget=django.forms.PasswordInput(render_value=False, attrs={'placeholder': 'password', 'class': 'input', 'style': 'color: white;'})
    )

    confirm_password = django.forms.CharField(
        widget=django.forms.PasswordInput(attrs={'placeholder': 'RepeatPassword', 'class': 'input', 'style': 'color: white;'})
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise django.forms.ValidationError("Email already exists")
        return email

    def clean_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.data['confirm_password']
        if password != confirm_password:
            raise django.forms.ValidationError("password does not matched")
        return password

class LoginForm(django.forms.Form):
    email = forms.EmailField(
        min_length=6, max_length=40,
        widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Email Address', 'style': 'background-color: light-grey;'})
    )
    password = forms.CharField(
        min_length=6, max_length=20,
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Password'})
    )

class YoutubeUrlForm(forms.Form):
    video_id = forms.CharField(
        min_length=10, max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Enter Urls here'})
    )

    def clean_video_id(self):
        video_url = self.cleaned_data['video_id']
        if YoutubeVideoId.objects.filter(video_url=video_url).exists():
            raise forms.ValidationError("Video url already exists")
        return video_url


# class SentimentAnalyzeForm(forms.Form):
#     input_text = forms.CharField(
#         min_length=10, max_length=100,
#         widget=forms.TextInput(attrs={'class': 'form-control px-4', 'placeholder': 'Enter Text here'})
#     )

class SentimentAnalyzeForm(forms.Form):
    input_text = forms.CharField(
        min_length=10, max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control px-4', 'placeholder': 'Enter Text here'})
    )

from django import forms

class SpamDetectionForm(forms.Form):
    input_text = forms.CharField(
        max_length=500, min_length=10,
        widget=forms.TextInput(attrs={'class': 'form-control px-4', 'placeholder': 'Enter Text here'})
    )

templates/about.html
{% extends 'master.html' %}

{% load static %}

{% block page-title %}About Us{% endblock %}

{% block page-styles %}{% endblock %}


{% block page-content %}
	
<div class="about-section">
  <h1 style="font-size: 50px;">About Us </h1>
  <p> </p>
  <p> </p>
</div>

<h2 style="text-align:center; padding:20px; font-size: 50px;">Our Team</h2>
<div class="row">
  <div class="column">
    <div class="cardd">
      <img src="{% static 'images/sakina.png' %}" alt="sakina" style="width:100%">
      <div class="containn ">
        <h2>Sakina Shahzad</h2>
        <p class="title">Programmer</p>
        <p> developing the software or application based on the project requirements.</p>
        <br><p>sakinashahzad789@gmail.com</p><br>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="cardd">
      <img src="{% static 'images/moon.png' %}"  alt="Moon" style="width:100%"  >
      <div class="containn">
        <h2>Moon Haider</h2>
        <p class="title">Web Designer</p>
        <p>creating the visual elements, layout, and overall design of website.</p>
        <br><p>moonhaider7602@gmail.com</p><br>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="cardd">
      <img src="{% static 'images/zoha.png' %}"  alt="zoha" style="width:100%">
      <div class="containn">
        <h2>Zoha Eman</h2>
        <p class="title"> Project Manager</p>
<p> Overseeing and coordinating all aspects of project to ensure its successful completion</p><br>
        <p>zohaeeman21@gmail.com</p><br>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>	
	

{% endblock %}

{% block page-scripts %}{% endblock %}
	

	
	
	
	

templates/comment-fetching.html
{% extends 'master.html' %}

{% load static %}

{% block page-title %}Youtube Sentiment Analysis{% endblock %}

{% block page-styles %}{% endblock %}


{% block page-content %}

    <p style="font-size: 40px; text-align: center; margin-top: 6%;"><b>COMMENTS FETCHING</b></p>

    <div class="m2">
  <div class="p1">
    <b style="padding: 3%; font-family: 'Your Desired Font', sans-serif; font-size: 24px;">INSERT URL</b>
    <div id="myform", style="padding: 1%; margin: 5px">
          <form method="post" class="narrow-w form-search d-flex align-items-stretch mb-3" data-aos="fade-up"
            data-aos-delay="100" style="padding: 1%;">
        {% csrf_token %}
        {% for field in yt_form %}
        <div class="form-group mb-20">
          <div class="input-group">
            <input type="text" name="{{ field.name }}" class="input-field input"
                   placeholder="Enter URL here"
                   style="height: 20px; width: 80%; background-color: gray; border-radius: 3px; color: #fff;
                          font-size: 15px; padding: 3%;
                          outline: none;">
          </div>
          {% if field.errors %}
          {% for error in field.errors %}
          <div class="col-md-11 alert-danger m-2" style="font-size: large;">{{ error }}</div>
          {% endfor %}
          {% endif %}
        </div>
        {% endfor %}
 <button type="submit" class="btn btn-primary" style="margin-top: 10px; margin-left: 0px">Search</button>
      </form>
    </div>


  </div>

  <div class="p2">
    <a href="{% url 'cfetch' %}"><img src="{% static 'images/sentiment-analysis-for-youtube-comments.heic' %}"
                                      alt="logo" width="98%"></a>
  </div>
</div>

    <br>

  <div class="table">
    <table style="width:80%; border-collapse: collapse; margin: 20px auto; border: 1px solid #ccc;">
        <tr>
            <th style="padding: 10px; border: 1px solid #ccc;">No.</th>
            <th style="padding: 10px; border: 1px solid #ccc;">Video ID</th>
            <th style="padding: 10px; border: 1px solid #ccc;">Comments</th>
            <th style="padding: 10px; border: 1px solid #ccc;">Sentiment Options</th>
        </tr>
        {% for video in videos %}
            <tr>
                <td style="padding: 10px; border: 1px solid #ccc;">{{ forloop.counter }}</td>
                <td style="padding: 10px; border: 1px solid #ccc;"><a href="{{ video.video_url }}", style="color: black;">{{ video.id }}</a></td>
                <td style="padding: 10px; border: 1px solid #ccc;">{{ video.comment_video.count }}</td>
                <td style="padding: 20px; border: 1px solid #ccc; margin: 5%">
                        <a href="/eng-comments/{{ video.id }}/" type="button" class="btn">
                            English
                        </a>

                        <a href="/emoji-comments/{{ video.id }}/" type="button" class="btn">
                            Emoji
                        </a>
                    </td>
            </tr>
        {% endfor %}
    </table>
</div>

    {##}
    {##}
    {#<p style="font-size: 25px; margin-left: 25px;"><b>Comments data in csv file</b> </p>#}
    {#<form class="form-contain">#}
    {#    <label for="w3review"></label>#}
    {#    <textarea id="w3review" name="w3review" rows="20" cols="160"></textarea>#}
    {#</form>#}

    <!-- Table for top 5 comments -->
    {#{% if top_comments %}#}
    {#<div class="table">#}
    {#    <table border="4px" cellpadding="30px" cellspacing="5px">#}
    {#        <thead>#}
    {#            <tr>#}
    {#                <th>Comment ID</th>#}
    {#                <th>Comment</th>#}
    {#            </tr>#}
    {#        </thead>#}
    {#        <tbody>#}
    {#            {% for comments in top_comments %}#}
    {#            <tr>#}
    {#                <td>{{ forloop.counter }}</td>#}
    {#                <td>{{ comments }}</td>#}
    {#            </tr>#}
    {#            {% endfor %}#}
    {#        </tbody>#}
    {#    </table>#}
    {#</div>#}
    {#{% endif %}#}
    {##}
    {#<div class="my-btn" style="text-align: center;">#}
    {#  <p style="font-size: 18px; color: #333; font-weight: bold;">Want the full dataset?</p>#}
    {#  <p style="font-size: 16px; color: #777; margin-bottom: 10px;">Click the button below to save all the comments.</p>#}
    {#  <form action="{% url 'save_csv' %}" method="POST">#}
    {#    {% csrf_token %}#}
    {#    <button type="submit" class="btn" style="margin-left: 25px; padding: 10px 15px; font-size: 18px; color: white; border: none; border-radius: 4px; cursor: pointer;">Save Comments</button>#}
    {#  </form>#}
    {#</div>#}
    {##}
    {#    <div class="my-btn" style="text-align: center;">#}
    {#  <p style="font-size: 18px; color: #333; font-weight: bold;">Want to clean comments?</p>#}
    {#  <p style="font-size: 16px; color: #777; margin-bottom: 10px;">Click the button below to clean the comments.</p>#}
    {#  <form action="{% url 'clean_comments' %}" method="POST">#}
    {#    {% csrf_token %}#}
    {#    <button type="submit" class="btn" style="margin-left: 25px; padding: 10px 15px; font-size: 18px; color: white; background-color: #f44336; border: none; border-radius: 4px; cursor: pointer;">Clean Comments</button>#}
    {#  </form>#}
    {##}
    {#  {% if message %}#}
    {#    <p style="font-size: 16px; color: #333; margin-top: 10px;">{{ message }}</p>#}
    {#  {% endif %}#}
    {#</div>#}


    <p style="font-size: 25px; text-align: center; padding: 30px;"><b>Do you want to analyze sentiment or to detect
        spam?</b></p>

    <div class="my-btnn">
        <div style="text-align: center;">
            <a href="{% url 'a-visualize' %}">
                <button type="submit" class="btn">Analyzer</button>
            </a>
            <a href="{% url 'sdetection' %}">
                <button type="submit" class="btn">Detector</button>
            </a>
        </div>
    </div>

    <br><br>

{% endblock %}

{% block page-scripts %}{% endblock %}

templates/emj_comment.html
{% extends 'master.html' %}

{% load static %}

{% block page-title %}Youtube Sentiment Analysis{% endblock %}

{% block page-styles %}{% endblock %}

{% block page-content %}

<br>
    <br>
    <h1 style="text-align: center;">EMOJI COMMENTS VISUALIZATION</h1>
 <br>
    <br>
    <div class="section" style="align-items: center;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Graph 1</h2>
                <div style="margin: 10px;">
                    {{ gr1|safe }}
                </div>
            </div>
            <br>
            <div class="col-lg-12">
                <h2>Graph 2</h2>
                <div style="height:500px; width: 400px; margin: 10px;">
                    {{ gr2|safe }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/eng_comment.html
{% extends 'master.html' %}

{% load static %}

{% block page-title %}Youtube Sentiment Analysis{% endblock %}

{% block page-styles %}{% endblock %}

{% block page-content %}
    <br>
    <br>
    <h1 style="text-align: center;">ENGLISH COMMENTS VISUALIZATION</h1>
 <br>
    <br>
    <div class="section" style="align-items: center;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Graph 1</h2>
                <div style="margin: 10px;">
                    {{ gr1|safe }}
                </div>
            </div>
            <br>
            <div class="col-lg-12">
                <h2>Graph 2</h2>
                <div style="margin: 10px;">
                    {{ gr2|safe }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
{% load static %}
<footer>
    <div class="footer_container  ">
        <div class="footer_logo">
            <img src="{% static 'images/pngegg.png' %}" alt="logo"
                 width="80px"/>
        </div>
        <div class="link_lists">
            <h1 style="color: darkred;"><b>Main Links</b></h1>
            <ul>
                <li><a href="{% url 'cfetch' %}">Comments Fetching</a></li>
                <li><a href="{% url 'sanalysis' %}">Sentiment Analysis</a></li>
                <li><a href="{% url 'sdetection' %}">Spam Detection</a></li>
                <li><a href="{% url 'models' %}">ML Models</a></li>
            </ul>
        </div>
        <div class="link_lists">
            <h1><b>Support</b></h1>
            <ul>
                <li><a href="{% url 'aboutus' %}">About Us</a></li>
                <li><a href="{% url 'aboutus' %}">Privacy Policy</a></li>
                <li><a href="{% url 'aboutus' %}">Contact Us</a></li>

            </ul>
        </div>
        <div class="news_letter">
            <h3 style="color: darkred; ; "><b>Message...</b></h3>
            <label>
                <input type="email" placeholder="Enter your Message..." style="height:35px"/>
            </label>
            <button type="submit" style="background-color: grey; ">ok</button>
            <h3 style="color: white;"><b>Follow Us</b></h3>
            <div class="icon_container">
                <div class="icon">
                    <img src="{% static 'images/Youtube Icon.png' %}" alt="logo"
                         width="40px">
                </div>
                <div class="icon">
                    <img src="{% static 'images/kindpng_300712.png' %}" alt="logo"
                         width="40px">
                </div>
                <div class="icon">
                    <img src="{% static 'images/instagram.png' %}" alt="logo"
                         width="45px">
                </div>
                <div class="icon">
                    <img src="{% static 'images/Facebook.png' %}" alt="logo"
                         width="50px">
                </div>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
<header>
    <nav class="container">
        <div class="logo">
            <a href="{% url 'homepage' %}"> <img src="{% static 'images/pngegg.png' %}" width="100%" alt="logo "  ></a></div>
        <ul>
            <div class="dropdown">
                <a href="{% url 'homepage' %}">
                     <li style="font-size: 18px;"> Home<img src="{% static 'images/white-triangle-icon-10.jpg' %}" width="12px" height="4%" alt="logo" style=" margin-left: 9px;">
                </a>
                        <div class="dropdown-content">
                            <a href="{% url 'models' %}">Models</a>
                        </div>

            </div>



                    <li style="font-size: 18px;"> <a href="{% url 'cfetch' %}">Comment Fetching </a></li>


                    <li style="font-size: 18px;"><a href="{% url 'sentiment_analysis' %}">Sentiment Analysis</a></li>


                    <li style="font-size: 18px;"><a href="{% url 'spam_detection' %}">Spam Detection</a></li>


                    <li style="font-size: 18px;"><a href="{% url 'aboutus' %}"> About Us</a></li>


                    <li style="font-size: 18px;"> <a href="{% url 'index' %}">Logout</a></li>


        </ul>
    </nav>
</header>

templates/homepage.html
{% extends 'master.html' %}
{% load static %}
{% block page-title %}Youtube Sentiment Analysis{% endblock %}
{% block page-styles %}{% endblock %}
{% block page-content %}
<div id="mainn"  >
    <div>
        <div style="text-align: center;">
            <br>
            <h1 style="font-size: 40px; color:lemonchiffon; font-family:sans-serif "><b>Youtube Sentiment Analysis</b></h1><br>
            <p style="font-size: 25px; text-align:center; color:white; "> The process of analyzing and understanding the
                sentiment or emotions expressed by users in the comments, likes, dislikes, and other interactions on
                YouTube videos.The main objective of YouTube sentiment analysis is to determine whether the sentiment
                expressed by users is positive, negative, or neutral towards a particular video or topic.
            </p><br>
            <button class="explore_btn"><a href="{% url 'cfetch' %}">Get Started Now </a></button>
        </div>
    </div>
    <br>
    <div>
        <div style="text-align: center;">
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                 src="{% static 'images/youtube-users-960x502.webp' %}">
        </div>
    </div>
    </div>
    <div style="text-align: center;"><p style="font-size: 60px; margin-top:10%; font-family:'bigshot-one',serif;"><b>Categorize</b></p></div>
    <div class="m1">
        <div class="p1">
            <div style="text-align: center;">
                <b> Comments Fetching</b>
            </div>
            <p style="padding: 25px;">YouTube comment fetching is the process of retrieving comments from YouTube videos. This can be done using the YouTube Data API, which provides a programmatic way to access YouTube data. To fetch comments, you need to create a project in the Google Developers Console and enable the YouTube Data API. Once you have enabled the API, you can use the API Explorer to generate code that will fetch comments from a YouTube video.
                The YouTube Data API allows you to fetch comments in a variety of ways. You can fetch all comments for a video, or you can fetch comments that meet certain criteria, such as comments that were posted within a certain time period or comments that have a certain number of likes.</p>
        </div>
        <div class="p2">
            <a href="{% url 'cfetch' %}"><img
                    src= "{% static 'images/sentiment-analysis-for-youtube-comments.heic' %}" alt="logo" style="width: 98%; height: 300px;"></a>
        </div>
    </div>
    <div class="m1">
        <div class="p2">
            <a href="{% url 'sanalysis' %}"> <img
                    src="{% static 'images/sentiment_analysis.jpg' %}" alt="logo"
                    style="width: 98%; height: 320px;"></a>
        </div>
        <div class="p1">
            <div style="text-align: center;">
                <b> Sentiment Analysis</b>
            </div>
            <p style="padding: 25px;">YouTube sentiment analysis is the process of extracting the sentiment, or opinion, of users from their comments on YouTube videos. This can be done using a variety of techniques, such as natural language processing (NLP) and machine learning. Sentiment analysis can be used for a variety of purposes, such as: Understanding user sentiment, Identifying trends and to Get feedback. Sentiment analysis is a powerful tool that can be used to understand user sentiment, identify trends, and get feedback. If you are interested in using sentiment analysis for your YouTube videos, I recommend that you check out the resources above.</p>
        </div>
    </div>
    <div class="m1">
        <div class="p1">
            <div style="text-align: center;">
                <b> Spam Detection</b>
            </div>
            <p style="padding: 25px;">YouTube spam detection is the process of identifying and removing spam comments from YouTube videos. Spam comments are typically irrelevant, off-topic, or promotional in nature. They can also be harmful, such as containing phishing links or malware. There are a variety of techniques that can be used to detect spam comments, including: Content analysis, User behavior analysis and Machine learning. YouTube uses a combination of these techniques to detect spam comments. Once a spam comment is detected, it is removed from the video and the user who posted the comment may be blocked from commenting on YouTube. YouTube spam detection is an ongoing challenge. Spammers are constantly developing new techniques to evade detection. However, by using a variety of techniques.</p>
        </div>
        <div class="p2">
            <a href="{% url 'sdetection' %}"> <img
                    src="{% static 'images/youtube-analytics-63db7f2648c60-sej-760x400.webp' %}" alt="logo"
                    style="width: 97%; height: 290px;"></a>
        </div>
    </div>
 {% endblock %}
{% block page-scripts %}{% endblock %}

templates/spam-detection.html
{% extends 'master.html' %}

{% load static %}

{% block page-title %}Spam Detection{% endblock %}

{% block page-styles %}{% endblock %}

{% block page-content %}
<div class="m2">
    <div class="p1">
        <h1 style="font-size: 40px; padding: 25px; align-items: center;"><b>Spam Detection</b></h1>
        <p style="font-size: 130%; text-align: justify; padding: 25px;">
            YouTube spam detection is an algorithm that automatically identifies and filters out spam comments on YouTube videos, ensuring a cleaner and more relevant comment section for users. It uses various techniques like content analysis, pattern recognition, and machine learning to accurately identify and flag spam comments. Spam detection in YouTube involves identifying and filtering out irrelevant, misleading, or malicious content that violates YouTube's policies and guidelines.
        </p>
        <a href="/svisualize/" class="btn">Visualization</a>
    </div>
    <div class="p2">
        <a href="{% url 'sdetection' %}"><img src="{% static 'images/spam-messages-detection.png' %}" alt="logo" width="98%"></a>
    </div>
</div>

<div class="analyzer">
    <div class="form">
        <h2>Spam Detector</h2>
        <br>
        <form method="post">
    {% csrf_token %}
    <div class="form-row align-items-center">
{#        <div class="col-auto">#}
{#            <input type="text" name="input_text" id="id_input_text" placeholder="Enter Text here">#}
            {{ spam_form.input_text }}
            {% if spam_form.input_text.errors %}
                <span class="error">{{ spam_form.input_text.errors }}</span>
            {% endif %}
{#        </div>#}
{#        <div class="col-auto">#}
            <button type="submit" class="btn">Detect</button>
        </div>
</form>
{% if predicted_labels %}
            <div>
                <h3 style="color: black">Predicted Label: {{ predicted_labels }} </h3>
            </div>
{% endif %}
{#</div>#}
    </div>
</div>


{% endblock %}

{% block page-scripts %}{% endblock %}